'''
Map a set of changed files onto the images that have to be rebuilt.

Run by ci.yml's `changes` job, which has no installed package and no
dependencies -- so everything here is standard library, and nothing imports
_image_deps (which shells out to a real interpreter per entrypoint and would
need the project installed). The measured closure this reads was generated by
_image_deps at commit time and lives in docs/image-closure.json.

    python -m tests.cli._affected_images --base "$BASE_SHA" --head HEAD

It lives under tests/ for the same reason the engines in tests/fakes/ do: no
image copies tests/, and pyproject's packages.find already excludes `tests*`,
so a CI helper placed here cannot accidentally ship inside the thing it is
deciding how to build.

WHY IT CAN FAIL
---------------
A file the closure claims for no image is an error, not an empty answer. The
2026-09-04 finding is the precedent: a green matrix that published nothing for
four days, because nothing was looking. "No image needs this" and "the graph
does not know about this yet" are indistinguishable from the outside, and only
one of them is safe to skip -- so the ambiguous case fails loudly instead.

A DELETION IS NOT AN ORPHAN
---------------------------
A module deleted in this very change is absent from the head closure, which
looks exactly like a module no image claims. Attributing it by the BASE
closure is what tells those apart: the deleted file's old owners are the images
whose contents really did change. #956 and #957 both deleted modules, and a
filter without this would have failed on each of them.
'''
import argparse
import json
import subprocess  # nosec B404 - fixed argv, no shell, reads git metadata only
import sys
from pathlib import Path

from tests.cli._roots import root_of

REPO_ROOT = Path(__file__).resolve().parents[2]
CLOSURE_PATH = 'docs/image-closure.json'

# Inputs that are not python modules. VERSION and docker/entrypoint.sh are
# genuinely all-six -- every image COPYs both. alembic/ is COPYd by
# Dockerfile.db alone. The bare, repo-root pyproject.toml is deliberately
# ABSENT from this list: since criterion 8 step 5 gave each package its own
# pyproject.toml, the root one holds only the `test` extra and shared tool
# config, and installs no production package at all -- a change there reaches
# no deployed image, which `images_for_pyproject` below derives rather than
# this list declaring.
#
# Everything else under docker/ -- the .cnf.example files, the compose file --
# matches the old `docker/*` filter but is copied by no Dockerfile, so it
# rebuilt six images and changed none of them.
ALWAYS_ALL = ('VERSION', 'docker/entrypoint.sh')
DB_ONLY_PREFIXES = ('alembic/',)
DB_ONLY_FILES = ('alembic.ini',)


def module_for(path: str) -> str | None:
    '''`discord_bot/a/b.py` -> `discord_bot.a.b`; None if not a first-party module.

    The root is looked up in `_roots.ROOTS` rather than spelled `discord_bot/`
    here, because criterion 8 hoists each folder to its own top-level package
    and a path this does not recognise contributes NO images -- which builds
    nothing, silently, for exactly the files a migration is moving. Both
    spellings answer while the tree is half-moved.

    An UNDECLARED root is still None, and that is the case the equality check on
    ROOTS covers: recognising any `*/**.py` would make `scripts/foo.py` an
    orphan and fail CI on a file that should build nothing.
    '''
    if root_of(path) is None or not path.endswith('.py'):
        return None
    module = path[: -len('.py')].replace('/', '.')
    if module.endswith('.__init__'):
        module = module[: -len('.__init__')]
    return module


def images_for_pyproject(path: str, claims: dict) -> set:
    '''
    Which images a pyproject.toml edit actually reaches.

    The whole file used to count as an all-six input, which is how a pylint
    bump rebuilt and rescanned six images that do not install pylint. That
    changed once already, when per-image extras made it possible to resolve
    each image's own extra through its `discord_bot[...]` self-references and
    check whether a changed extra was inside it -- but criterion 8 step 5
    retired the extras themselves, so that graph no longer exists to read.

    The bare, repo-root pyproject.toml (this function is never called for it --
    see the `ALWAYS_ALL` comment) reaches no image at all now. Every OTHER
    pyproject.toml lives inside one of the seven package roots and changes
    that root's real `dependencies`, so the answer is the same one a .py
    module change under that root already gets: whichever images' MEASURED
    closure claims a module under it. A discord_core/pyproject.toml edit
    reaches all six, the same as any other discord_core change; a pod's own
    reaches only that pod's image.
    '''
    root = root_of(path)
    if root is None:
        return set()
    return {image for image, mods in claims.items()
            if any(m.startswith(f'{root}.') for m in mods)}


def affected(changed_files, deleted_files, head_closure, base_closure):
    '''
    Return (images_to_build, orphan_paths).

    `deleted_files` comes from git (`--diff-filter=D`) rather than from asking
    the filesystem whether each path still exists. Those are not the same
    question: a working tree can disagree with the diff being evaluated, and
    "which files did this change delete" is exactly what git already knows.
    Taking it as an argument also keeps this function pure, so the interesting
    cases are stated in tests rather than staged as commits.

    Orphans are reported rather than raised so the caller decides what a build
    failure looks like; every other unrecognised path contributes no images,
    which is the point -- a README edit builds nothing.
    '''
    claims = {i['image']: set(i['modules']) for i in head_closure['images']}
    base_claims = {i['image']: set(i['modules']) for i in base_closure['images']} if base_closure else {}
    dockerfiles = {i['dockerfile']: i['image'] for i in head_closure['images']}
    every = set(claims)
    db_image = next((i['image'] for i in head_closure['images']
                     if i['entrypoint'].endswith('.database')), None)

    deleted = set(deleted_files)
    images, orphans = set(), []
    for path in changed_files:
        module = module_for(path)
        if module is not None:
            owners = {image for image, mods in claims.items() if module in mods}
            if owners:
                images |= owners
            elif path in deleted:
                # Deleted here: the images that carried it are the ones that changed.
                # Falling back to every image when the base closure is unavailable
                # over-builds, which is the safe direction for a deletion.
                images |= {image for image, mods in base_claims.items() if module in mods} or every
            else:
                orphans.append(path)
        elif path in ALWAYS_ALL:
            images |= every
        elif path.endswith('pyproject.toml'):
            images |= images_for_pyproject(path, claims)
        elif path in dockerfiles:
            images.add(dockerfiles[path])
        elif path.startswith(DB_ONLY_PREFIXES) or path in DB_ONLY_FILES:
            if db_image:
                images.add(db_image)
    return images, orphans


def _git_show(ref: str, path: str) -> str:
    '''File contents at `ref`, or '' when it is not there.'''
    result = subprocess.run(['git', 'show', f'{ref}:{path}'],  # nosec B603 B607 - fixed argv
                            cwd=REPO_ROOT, capture_output=True, text=True, check=False)
    return result.stdout if result.returncode == 0 else ''


def main(argv=None) -> int:
    '''Print the build matrix for the changed files, or fail on an orphan.'''
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--base', required=True, help='base ref to diff against')
    parser.add_argument('--head', default='HEAD', help='head ref (default HEAD)')
    args = parser.parse_args(argv)

    def _names(*extra):
        result = subprocess.run(  # nosec B603 B607 - fixed argv
            ['git', 'diff', '--name-only', *extra, f'{args.base}...{args.head}'],
            cwd=REPO_ROOT, capture_output=True, text=True, check=True)
        return [line.strip() for line in result.stdout.splitlines() if line.strip()]

    changed = _names()
    deleted = _names('--diff-filter=D')

    head_closure = json.loads((REPO_ROOT / CLOSURE_PATH).read_text(encoding='utf-8'))
    base_raw = _git_show(args.base, CLOSURE_PATH)
    base_closure = json.loads(base_raw) if base_raw else None

    images, orphans = affected(changed, deleted, head_closure, base_closure)

    print('changed files:', file=sys.stderr)
    for path in changed:
        print(f'  {path}', file=sys.stderr)

    if orphans:
        print('\nERROR: these files belong to no image closure:', file=sys.stderr)
        for path in orphans:
            print(f'  {path}', file=sys.stderr)
        print(
            '\nA module no entrypoint reaches is either dead code or a gap in the\n'
            'measured graph, and CI cannot tell which. Building nothing would ship it\n'
            'untested. Either delete it, or make an entrypoint reach it, then\n'
            'regenerate with:\n'
            '    UPDATE_IMAGE_DEPS=1 pytest tests/cli/test_import_boundaries.py',
            file=sys.stderr)
        return 1

    ordered = sorted(images)
    by_name = {i['image']: i for i in head_closure['images']}
    matrix = {'include': [{'image': name, 'dockerfile': by_name[name]['dockerfile']}
                          for name in ordered]}
    print(f'\nimages to build: {", ".join(ordered) or "(none)"}', file=sys.stderr)
    print(f'images={json.dumps(ordered)}')
    print(f'matrix={json.dumps(matrix)}')
    print(f'any={"true" if ordered else "false"}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
