[tox]
min_version = 4.0
env_list =
    py311
    py312
    py313
    py314

[testenv]
extras = bot,test
passenv =
    POSTGRES_TEST_HOST
    POSTGRES_TEST_PORT
    POSTGRES_TEST_USER
    POSTGRES_TEST_PASSWORD
setenv =
    POSTGRES_TEST_HOST = {env:POSTGRES_TEST_HOST:localhost}
    POSTGRES_TEST_PORT = {env:POSTGRES_TEST_PORT:5432}
    POSTGRES_TEST_USER = {env:POSTGRES_TEST_USER:postgres}
    POSTGRES_TEST_PASSWORD = {env:POSTGRES_TEST_PASSWORD:postgres}
allowlist_externals =
    sh
commands_pre =
    sh tests/start_postgres_for_ci.sh
commands =
    pylint discord_bot/
    pylint --rcfile .pylintrc.test  tests/
    bandit -r discord_bot/
    pytest --cov=discord_bot --cov-report=xml --cov-fail-under=99 tests/
