#!/bin/bash

set -eux;

{
    # https://stackoverflow.com/questions/32104702/youtube-dl-library-and-error-403-forbidden-when-using-generated-direct-link-by
    youtube-dl --rm-cache-dir

    # Check config for download dir
    DOWNLOAD_DIR="/tmp/"
    if [ -f "/secret/discord.conf" ] ; then
        if grep -q "download_dir" "/secret/discord.conf" ; then
            DOWNLOAD_DIR=$(cat /secret/discord.conf | sed -nr 's/^download_dir=(.*)/\1/p')
        fi
    fi

    # Delete files older than 1 day
    find "$DOWNLOAD_DIR" -mtime +1 -delete
} >> /logs/cleanup-youtube.log 2>&1
