"""add storage to cache db

Revision ID: 0a3945d3e28b
Revises: 4c68f4df56dd
Create Date: 2026-03-20 15:01:57.264324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3945d3e28b'
down_revision: Union[str, Sequence[str], None] = '4c68f4df56dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_cache', sa.Column('storage_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_cache', 'storage_type')
    # ### end Alembic commands ###
