"""Added object storage backup table

Revision ID: 0f696315a882
Revises: bf24a336d155
Create Date: 2025-07-01 20:26:14.572146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f696315a882'
down_revision: Union[str, Sequence[str], None] = 'bf24a336d155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_cache_backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_cache_id', sa.Integer(), nullable=True),
    sa.Column('storage', sa.String(length=1024), nullable=True),
    sa.Column('bucket_name', sa.String(length=1024), nullable=True),
    sa.Column('object_path', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['video_cache_id'], ['video_cache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_cache_backup')
    # ### end Alembic commands ###
