"""Add file size column

Revision ID: 4c68f4df56dd
Revises: a399ba3deb56
Create Date: 2026-03-18 15:37:45.942141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c68f4df56dd'
down_revision: Union[str, Sequence[str], None] = 'a399ba3deb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_cache', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_cache', 'file_size_bytes')
    # ### end Alembic commands ###
