"""Removing search cache client

Revision ID: 5b627533b326
Revises: 0f696315a882
Create Date: 2025-08-03 12:35:00.906169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b627533b326'
down_revision: Union[str, Sequence[str], None] = '0f696315a882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_string')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_string',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_iterated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('search_string', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
