"""remove user_id and batch_id from video request analytics

Revision ID: 805bae71a46e
Revises: c7ea05bb7aa3
Create Date: 2025-08-04 22:54:40.800764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805bae71a46e'
down_revision: Union[str, Sequence[str], None] = 'c7ea05bb7aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_request_analytics', 'batch_id')
    op.drop_column('video_request_analytics', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_request_analytics', sa.Column('user_id', sa.VARCHAR(length=128), nullable=True))
    op.add_column('video_request_analytics', sa.Column('batch_id', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
