"""remove video cache guild table

Revision ID: 86418d6f1ce3
Revises: 491790be3ce3
Create Date: 2025-09-28 17:23:31.499064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86418d6f1ce3'
down_revision: Union[str, Sequence[str], None] = '491790be3ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_cache_guild')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_cache_guild',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('guild_id', sa.INTEGER(), nullable=True),
    sa.Column('video_cache_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], ),
    sa.ForeignKeyConstraint(['video_cache_id'], ['video_cache.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_cache_id', 'guild_id', name=op.f('_unique_cache_guild'))
    )
    # ### end Alembic commands ###
