"""add video request analytics table

Revision ID: c7ea05bb7aa3
Revises: 5b627533b326
Create Date: 2025-08-04 22:44:17.957412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ea05bb7aa3'
down_revision: Union[str, Sequence[str], None] = '5b627533b326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_request_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('video_url', sa.String(length=256), nullable=True),
    sa.Column('search_string', sa.String(length=512), nullable=True),
    sa.Column('search_type', sa.String(length=32), nullable=True),
    sa.Column('video_title', sa.String(length=1024), nullable=True),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('extractor', sa.String(length=256), nullable=True),
    sa.Column('cache_hit_pre_queue', sa.Boolean(), nullable=True),
    sa.Column('cache_hit_post_queue', sa.Boolean(), nullable=True),
    sa.Column('download_attempted', sa.Boolean(), nullable=True),
    sa.Column('download_successful', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('batch_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_request_analytics')
    # ### end Alembic commands ###
