"""add days column to video analytics

Revision ID: faa6198cbed2
Revises: 86418d6f1ce3
Create Date: 2025-12-15 15:29:43.565360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa6198cbed2'
down_revision: Union[str, Sequence[str], None] = '86418d6f1ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the new days column with default value of 0
    op.add_column('server_video_analytics', sa.Column('total_duration_days', sa.Integer(), nullable=False, default=0))

    # Step 2: Migrate existing data - split total_duration_seconds into days and remaining seconds
    # This ensures all seconds values will be < 86400 before we change the column type to Integer
    # Using CAST to ensure integer division works across different SQL databases
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE server_video_analytics
        SET total_duration_days = CAST(total_duration_seconds / 86400 AS INTEGER),
            total_duration_seconds = total_duration_seconds % 86400
        WHERE total_duration_seconds IS NOT NULL
    """))
    connection.commit()

    # Step 3: Now safe to change column type from BIGINT to Integer
    op.alter_column('server_video_analytics', 'total_duration_seconds',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_video_analytics', 'total_duration_seconds',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('server_video_analytics', 'total_duration_days')
    # ### end Alembic commands ###
