"""add days column to video analytics

Revision ID: faa6198cbed2
Revises: 86418d6f1ce3
Create Date: 2025-12-15 15:29:43.565360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa6198cbed2'
down_revision: Union[str, Sequence[str], None] = '86418d6f1ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_video_analytics', sa.Column('total_duration_days', sa.Integer(), nullable=True))
    op.drop_column('server_video_analytics', 'total_duration_seconds')
    op.add_column('server_video_analytics', sa.Column('total_duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_video_analytics', 'total_duration_days')
    # ### end Alembic commands ###
