version: '2'
services:
  db:
    image: postgres:16
    container_name: psql
    ports:
      - 5432:5432
    volumes:
      # Dont put this volume within the mounted volume on vbox
      # Else you hit all kinds of weird permissions stuff
      - ~/volumes/dbdata:/var/lib/postgresql/data
      # Copy this from files/init.sql over
      - ~/volumes/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      database_network:
  discord:
    build: .
    container_name: discord
    volumes:
      - ~/volumes/discord/downloads:/opt/discord/downloads
      - ~/volumes/discord/logs:/var/log/discord
      - ~/volumes/discord/discord.cnf:/opt/discord/discord.cnf
    environment:
      - POSTGRES_HOST=psql
      - POSTGRES_PASSWORD=${DISCORD_USER_PASSWORD}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_YOUTUBE_API_KEY=${DISCORD_YOUTUBE_API_KEY}
      - DISCORD_SPOTIFY_CLIENT_SECRET=${DISCORD_SPOTIFY_CLIENT_SECRET}
      - DISCORD_SPOTIFY_CLIENT_ID=${DISCORD_SPOTIFY_CLIENT_ID}
    networks:
      database_network:
    depends_on:
      - db


networks:
  database_network: