"""Initial migration

Revision ID: bf24a336d155
Revises: 
Create Date: 2025-06-26 18:05:12.580083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf24a336d155'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markov_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=128), nullable=True),
    sa.Column('server_id', sa.String(length=128), nullable=True),
    sa.Column('last_message_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'server_id', name='_unique_markov_channel')
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('server_id', sa.String(length=128), nullable=True),
    sa.Column('last_queued', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_history', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'server_id', name='_server_playlist')
    )
    op.create_table('search_string',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_iterated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('search_string', sa.String(length=2048), nullable=True),
    sa.Column('video_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('video_url', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('uploader', sa.String(length=1024), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('extractor', sa.String(length=256), nullable=True),
    sa.Column('last_iterated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('ready_for_deletion', sa.Boolean(), nullable=True),
    sa.Column('base_path', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markov_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('leader_word', sa.String(length=255), nullable=True),
    sa.Column('follower_word', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['markov_channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('video_url', sa.String(length=256), nullable=True),
    sa.Column('uploader', sa.String(length=256), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_url', 'playlist_id', name='_unique_playlist_video')
    )
    op.create_table('video_cache_guild',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.Column('video_cache_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], ),
    sa.ForeignKeyConstraint(['video_cache_id'], ['video_cache.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_cache_id', 'guild_id', name='_unique_cache_guild')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_cache_guild')
    op.drop_table('playlist_item')
    op.drop_table('markov_relation')
    op.drop_table('video_cache')
    op.drop_table('search_string')
    op.drop_table('playlist')
    op.drop_table('markov_channel')
    op.drop_table('guild')
    # ### end Alembic commands ###
