name: Coverage Upload

on:
  push:
    branches: [main]

jobs:
  store-coverage:
    uses: tnoff/github-workflows/.github/workflows/coverage-store.yml@c727d141564e2e8c86b1ac327df3698e0d521640
    with:
      coverage_source: discord_bot
      install_command: pip install -r requirements.txt -r requirements.sqlite.txt -r tests/requirements.txt
      python_version: 3.14
      pre_install_command: sudo apt-get update && sudo apt-get install -y sqlite3 ffmpeg