name: Tag and build docker image

on:
  push:
    branches:
    - main

jobs:
  tag_build:
    name: Tag Build if doesn't exist already
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Get version
        id: version
        run: echo "version=v$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Check If Tag already exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: ${{ steps.version.outputs.version }}
      - run: echo "Tag exists!"
        if: steps.check-tag.outputs.exists == 'true'
      - name: Add tag
        id: tag-version
        if: steps.check-tag.outputs.exists != 'true'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}
          tag_prefix: ''
  push_to_registry:
    name: Push Docker Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@e61c643fe47e53d3495405cc9f441b5da06ab1e9
      - name: Check labels
        if: ${{ !(contains(steps.pr-labels.outputs.labels, 'build-docker')) }}
        run: exit 0
      - name: Check out the repo
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        if: contains(steps.pr-labels.outputs.labels, 'build-docker')
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Get github hash
        id: github-hash
        run: echo "github_hash=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/discord-bot:latest,registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/discord-bot:${{ steps.github-hash.outputs.github_hash }}